service: s3-notifications # NOTE: update this with your service name

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs4.3
  iamRoleStatements:
    $ref: ./iamRoleStatements.json

functions:
  hello:
    description: Detect upload to S3
    memorySize: 1024
    timeout: 30
    handler: handler.dispatch
    events:
      - s3:
          bucket: s3-notification
          event: s3:ObjectCreated:*